apiVersion: apps/v1
kind: Deployment
metadata:
  name: javamaven
spec:
  selector:
    matchLabels:
      app: javamaven
  replicas: 3
  template:
    metadata:
      labels:
        app: javamaven
    spec:
      containers:
      - name: myacr032023
        image: myacr032023.azurecr.io/{{CONTAINER_IMAGE}}:{{CONTAINER_TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: javamaven-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: javamaven

