apiVersion: apps/v1
kind: Deployment
metadata:
  name: javamaven
spec:
  selector:
    matchLabels:
      app: javamaven
  replicas: 3
  template:
    metadata:
      labels:
        app: javamaven
    spec:
      containers:
      - name: myacr032023
        image: myacr032023.azurecr.io/javamavenapp:latest
        ports:
        - containerPort: 8080
