version: '3'
services:
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - JavaMaven.war:/usr/local/tomcat/webapps
  app:
    image: localdocker23/javasampletomcat:latest
